/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CollapsibleTree: typeof import('./src/components/CollapsibleTree.vue')['default']
    IndentedTree: typeof import('./src/components/IndentedTree.vue')['default']
    LogViewer: typeof import('./src/components/LogViewer.vue')['default']
    ObjectDescription: typeof import('./src/components/ObjectDescription.vue')['default']
    SvgTree: typeof import('./src/components/SvgTree.vue')['default']
    SvgTreeLinkPath: typeof import('./src/components/SvgTreeLinkPath.vue')['default']
    SvgTreeNodeItem: typeof import('./src/components/SvgTreeNodeItem.vue')['default']
    SvgTreeNodeLabel: typeof import('./src/components/SvgTreeNodeLabel.vue')['default']
  }
}
